feat: adds example app docs
aregee/design-system pull request #60
Opened 2020-05-04 12:13 UTC by riyalohia

### What does this implement/fix? Explain your changes.
Adds covid app tutorial

### Does this close any currently open issues?

...

### Any other comments?

...

### Dependent PRs/Commits

...

### Describe breaking changes, if any.

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch

2020-05-04 15:13 UTC, satyamyadav reviewed
The pull request type should be `docs`.

2020-05-04 16:53 UTC, satyamyadav requested changes

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +# COVID-19 Tracker App Tutorial
Heading should be `Tutorial` only, and `Covid-19 Tracker App` as a subheading.

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +Welcome! This tutorial will guide you in creating an awesome app with Innovaccer Design System. Here is a [preview](https://covid19-tracker.info/) of the app that we are going to build. This tutorial
Please add linebreak after `Welcome!`.

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +This tutorial is intended for people with all amounts of web development experience. If you want to jump straight to code, you may want to skip this tutorial and go to the [developer guidelines](http
The link should be https://github.com/aregee/design-system/blob/master/CONTRIBUTING.md or https://github.com/aregee/design-system/#-how-to-contribute

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +* NVM
Mentioning NVM is not needed.

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +## <a name="Installation"></a>Installation
This title should be `Initializing App`.

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +## <a name="APP_INIT"></a>Initialising app
The title should be `Installing component Library`.

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +Next, you need to install Innovaccer design system in your project. You need to follow the [developer guidelines](https://github.com/aregee/design-system/blob/master/README.md) steps to install the d
Add npm install command for library and then provide the link as to refer for more details.

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +![alt tag](./images/Covid-App.png)
Move preview under first title (introductory part).

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +## <a name="BUILDING_LANDING_PAGE"></a>Building Landing Page
Heading should be something like `Creating page grid` or `Adding grid to page` and then in description highlisht that we are building first page of app.

2020-05-04 16:53 UTC, satyamyadav commented on docs/AppTutorial.md
> +Now that we have fetched the required data, we can easily render them in our component. Now its time to build `Map component` using the fetched API data. Here is the preview of what you will build:
Highlight or add a heading to inform we are going to use visualization components.

2020-05-05 13:57 UTC, aditya-kumawat commented on docs/AppTutorial.md
> +![alt tag](./images/Footer.png)
Either update the image or code below it

2020-05-05 13:59 UTC, aditya-kumawat commented on docs/AppTutorial.md
> +    <Router basename={process.env.PUBLIC_URL}>
I guess process.env.PUBLIC_URL is for github pages. Replacing it with '/' would be better.

2020-05-05 14:02 UTC, aditya-kumawat commented on docs/AppTutorial.md
> +    <Text style={{ fontSize:'28px'}}>
Remove style
Not recommended.

2020-05-05 14:04 UTC, aditya-kumawat commented on docs/AppTutorial.md
> +</Row>
Update with correct code.

2020-05-05 15:49 UTC, satyamyadav approved these changes

2020-05-05 15:50 UTC, merged